CREATE TABLE `FF4J_PROPERTIES`
(`PROPERTY_ID` VARCHAR(100) NOT NULL,`CLAZZ` VARCHAR(100),
    `CURRENTVALUE` VARCHAR(200),`DESCRIPTION` VARCHAR(2000),`FIXEDVALUES` VARCHAR(20),
    PRIMARY KEY (`PROPERTY_ID`));